default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: manga_dev
  username: postgres
  password: 1234
  host: localhost
  port: 5432

test:
  <<: *default
  database: manga_test
  username: postgres
  password: 1234
  host: localhost
  port: 5432

production:
  <<: *default
  database: manga_prod
  url: <%= ENV['DATABASE_URL'] %>
